name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker images
        run: |
          docker buildx build --push=false -t frontend ./frontend
          docker buildx build --push=false -t backend ./user_management
        env:
          DOCKER_BUILDKIT: 1

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./frontend/Dockerfile ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/frontend
            scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./user_management/Dockerfile ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/user_management
            ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'docker build -t frontend /frontend && docker build -t backend /user_management && docker-compose up -d'
