name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker setup
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker buildx build --push=false -t frontend ./.frontend
        env:
          DOCKER_BUILDKIT: 1
      - name: Build Docker images
        run: docker buildx build --push=false -t backend ./.user_management
        env:
          DOCKER_BUILDKIT: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - name: Connect to EC2
        uses: aws-actions/ec2-ssh@v1
        with:
          instance-id: ${{ secrets.EC2_INSTANCE_ID }}
          private-key-file: ${{ secrets.SSH_PRIVATE_KEY }}
          user: ubuntu

      - name: Copy Dockerfiles (optional)
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./frontend/Dockerfile ubuntu@43.204.103.187:/path/on/ec2
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} ./user_management/Dockerfile ubuntu@43.204.103.187:/path/on/ec2

      - name: Build Docker images on EC2 (optional)
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@43.204.103.187 'docker build -t frontend . && docker build -t backend .'

      - name: Run docker-compose (detached mode)
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@43.204.103.187 'docker-compose up -d'
